# This file defines Continuous Integration (CI) tests for BRL-CAD using the
# Github Actions framework.  Currently it defines configurations for Windows,
# Linux and OSX.
#
# Initially we used examples to try and define one common configuration for all
# platforms, but that turned out to be more complex than it was worth.  The
# different platforms manifest different issues, and it is easier to keep the
# individual steps simple and address what needs addressing per-platform.
#
# For more information about available platforms for testing, see:
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
#
# The general rule when building in CI is to go more verbose in output settings
# rather than less, since iterative debugging isn't practical.  We also want to
# avoid parallel building - while that will sometimes catch dependency issues,
# it also makes the outputs far harder to interpret when there is a problem.
# Better to do parallel build debugging in an environment were more interactive
# and iterative debugging is available while preserving the readability of the
# CI outputs for other issues.
#
# Note that there is another reason not to do parallel runs; we have had some
# trouble with issues that appear to be related to files not being fully
# written out to disk. To try and help mitigate this, we don't want to stress
# the I/O subsystem any more than necessary:
#
# https://github.com/actions/runner/issues/718
#

name: BRL-CAD

on: [push]

jobs:
  windows:
    name: Windows Latest MSVC
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup - CMake
        uses: lukka/get-cmake@latest

      - name: Setup - Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add github workspace to path
        # https://github.community/t/deprecated-add-path/136621
        run: echo "$ENV{GITHUB_WORKSPACE}" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Add cl.exe to PATH
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_C_COMPILER="cl.exe" -D CMAKE_CXX_COMPILER="cl.exe" -D ENABLE_ALL=ON -D CMAKE_BUILD_TYPE=Release
          # We do the following in order to help ensure files are "flushed"
          # to disk before compilation is attempted
          # https://superuser.com/a/1553374/1286142
          powershell Write-VolumeCache C
          powershell Write-VolumeCache D

      - name: Build
        run: cd build && ninja -j1 -v && ninja check -v && ninja package

        # Various other Windows build lines used for various types of testing.
        # Preserved for reference, as the iterative time to figure out how to
        # perform them was significant...
        #run: cmake --build build --config Release --target package
        #run: cd build && ninja -j1 -v STEPCODE_BLD && cd src/other/ext/STEPCODE_BLD-prefix/src/STEPCODE_BLD-build && ninja clean && ninja -j1 -v
        #run: cmake --build build --config Release --target STEPCODE_BLD && cd build/src/other/ext/STEPCODE_BLD-prefix/src/STEPCODE_BLD-build && msbuild ALL_BUILD.vcxproj -t:clean && msbuild ALL_BUILD.vcxproj -v:diag

        # For the moment the space demands are too extreme to enable this
        # output for every compile test, but leave the enabling logic present
        # in commented out form so it can be enabled as needed.
#     - name: Upload Package
#       uses: actions/upload-artifact@v2
#       with:
#         name: BRLCAD_Windows
#         path: ${{ github.workspace }}/build/BRL-CAD*exe

  linux:
    name: Ubuntu Latest GCC
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
      - name: Setup - CMake
        uses: lukka/get-cmake@latest

      - name: Setup - Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup - System
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          # Install X/OpenGL dev pkgs
          sudo apt-get install xserver-xorg-dev libx11-dev libxi-dev libxext-dev libglu1-mesa-dev
          sudo apt-get clean

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure
        run: |
          export PATH=$ENV{GITHUB_WORKSPACE}:$PATH
          cmake -S . -G Ninja -B build -D ENABLE_ALL=ON -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          export PATH=$ENV{GITHUB_WORKSPACE}:$PATH
          cmake --build build --config Release --target check
          cmake --build build --config Release --target package

        # For the moment the space demands are too extreme to enable this
        # output for every compile test, but leave the enabling logic present
        # in commented out form so it can be enabled as needed.
#     - name: Upload Package
#       uses: actions/upload-artifact@v2
#       with:
#         name: BRLCAD_Linux
#         path: ${{ github.workspace }}/build/BRL-CAD*gz

  osx:
    name: macOS Latest Clang
    runs-on: macos-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup - CMake
        uses: lukka/get-cmake@latest

      - name: Setup - Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure
        run: |
          export PATH=$ENV{GITHUB_WORKSPACE}:$PATH
          export CC=clang
          export CXX=clang++
          cmake -S . -G Ninja -B build -D ENABLE_ALL=ON -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          export PATH=$ENV{GITHUB_WORKSPACE}:$PATH
          cd build && ninja -j1 && ninja -j1 package
          #cmake --build build --config Release --target check
          #cmake --build build --config Release --target package

        # For the moment the space demands are too extreme to enable this
        # output for every compile test, but leave the enabling logic present
        # in commented out form so it can be enabled as needed.
#     - name: Upload Package
#       uses: actions/upload-artifact@v2
#       with:
#         name: BRLCAD_OSX
#         path: ${{ github.workspace }}/build/BRL-CAD*gz


